data_path: ../data/RevisitPinkerAndPrince/experiment_1/english_merged.txt
use_phonological: true
training_regime: oversample
use_slots: false
d_model: 128
nhead: 4
enc_layers: 2
dec_layers: 2
d_ff: 256
dropout: 0.3
lstm_hidden: 0
batch_size: 32
weight_decay: 0.0001
epochs: 200
patience: 30
retrieval_k: 5
plot_every: 10
track_val_split: true
encoder_type: bilstm
decoder_type: lstm
use_copy: false
use_retrieval: false
lr: 0.001
seed: 5
save_dir: ../checkpoints/v29_lstm_no_s5
results_dir: ../results/v29_lstm_no_s5
