alpha_recon: 0.0
batch_size: 64
d_ff: 128
d_model: 64
data_path: ../data/RevisitPinkerAndPrince/experiment_1/english_merged.txt
dec_layers: 2
dropout: 0.1
enc_layers: 2
epochs: 2
l0_beta: 0.66
lambda_l0: 0.01
lr: 0.0003
nhead: 4
num_slots: 4
save_dir: ../checkpoints_test
results_dir: ../results_test
plot_every: 1
seed: 42
slot_iters: 3
use_phonological: true
weight_decay: 0.0001
